# Generated by Django 5.0.4 on 2024-04-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('technology', models.CharField(max_length=20, verbose_name='Tecnologia')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem')),
                ('link', models.URLField(blank=True, verbose_name='Link do Projeto')),
            ],
        ),
    ]
